In [2]:
import pandas as pd
from copy import deepcopy

In [3]:
df = pd.read_csv('/home/admin1/Shreenag/dataset.csv')

In [4]:
df

x1   x2
0  5.9  3.2
1  4.6  2.9
2  6.2  2.8
3  4.7  3.2
4  5.5  4.2
5  5.0  3.0
6  4.9  3.1
7  6.7  3.1
8  5.1  3.8
9  6.0  3.0

In [5]:
x1 = df['x1'].values

In [6]:
x1

array([5.9, 4.6, 6.2, 4.7, 5.5, 5. , 4.9, 6.7, 5.1, 6. ])

In [7]:
y1 = df['x2'].values

In [8]:
y1


array([3.2, 2.9, 2.8, 3.2, 4.2, 3. , 3.1, 3.1, 3.8, 3. ])

In [9]:
import numpy as np

In [10]:
def euclidean(a,b,ax=1):
    return np.linalg.norm(a-b,axis=ax)
k=3

In [11]:
x=np.array(list(zip(x1,y1)))

In [12]:
x


array([[5.9, 3.2],
       [4.6, 2.9],
       [6.2, 2.8],
       [4.7, 3.2],
       [5.5, 4.2],
       [5. , 3. ],
       [4.9, 3.1],
       [6.7, 3.1],
       [5.1, 3.8],
       [6. , 3. ]])

In [13]:
c_x=[6.2,6.6,6.5]

In [14]:
c_y=[3.2,3.7,3.0]

In [15]:
c_x


[6.2, 6.6, 6.5]

In [16]:
c_y

[3.2, 3.7, 3.0]

In [17]:
centroid=np.array(list(zip(c_x,c_y)))

In [18]:
centroid

array([[6.2, 3.2],
       [6.6, 3.7],
       [6.5, 3. ]])

In [19]:
i=1

In [20]:
for j in centroid:
    dist= np.linalg.norm(x[i]-j)
    print(dist)

1.6278820596099712
2.154065922853802
1.902629759044045


In [21]:
print(centroid.shape)

(3, 2)


In [22]:
centroid_old=np.zeros(centroid.shape)
print(centroid_old)
clusters = np.zeros(len(x))
print(clusters)
error=euclidean(centroid,centroid_old,None)
print(error)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
12.53714481052205


In [23]:
iterr=0
while error!=0:
    iterr=iterr+1
    for i in range(len(x)):
        distances=euclidean(x[i],centroid)
        cluster=np.argmin(distances)
        clusters[i]=cluster
    centroid_old=deepcopy(centroid)
    
    for p in range(k):
        points=[x[j] for j in range(len(x)) if clusters[j]==p]
        centroid[p]=np.mean(points,axis=0)
    print("Centre of cluster after", iterr,"iteration \n",centroid)
    error=euclidean(centroid,centroid_old,None)
    print("error...",error)

Centre of cluster after 1 iteration 
 [[5.17142857 3.17142857]
 [5.5        4.2       ]
 [6.45       2.95      ]]
error... 1.588639515498743
Centre of cluster after 2 iteration 
 [[4.8   3.05 ]
 [5.3   4.   ]
 [6.2   3.025]]
error... 0.548478879841925
Centre of cluster after 3 iteration 
 [[4.8   3.05 ]
 [5.3   4.   ]
 [6.2   3.025]]
error... 0.0
